name: Build and Test
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out source
        uses: actions/checkout@v1

      - name: Build
        env:
          GO111MODULE: "on"
        run: go build ./...

      - name: Run the test suite
        env:
          GO111MODULE: "on"
        run: |
          export GOPATH=$(go env GOPATH)
          export PATH=${PATH}:$(go env GOPATH)/bin
          make unit-race
